create table if not EXISTS Books (
    id int primary key GENERATED BY DEFAULT AS IDENTITY,
    author varchar(100),
    title varchar(100),
    year int,
    publisher varchar(100),
    price int,
    count int,
    page_count int
);

create table if not EXISTS Rols (
    id int primary key GENERATE BY DEFAULT AS IDENTITY,
    name_role varchar(20)
);

create table if not EXISTS Users (
    id int primary key GENERATE BY DEFAULT AS IDENTITY,
    name varchar(50),
    second_name varchar(50),
    last_name varchar(50),
    year int,
    email varchar(100),
    phone_number varchar(12),
    city varchar(50),
    role int references Rols(id)
);


--create table if not EXISTS BooksFromUser(
--    id int primary key GENERATE BY DEFAULT AS IDENTITY,
--    id_book references Books(id),
--    id_user references Users(id)
--);